@extends('frontend.layouts.app')
@section('content')

<section class="terms_conditions" style="margin-top: 100px; margin-bottom: 60px;">
<div class="container">  

<h3 style="font-weight: 600; font-size: 22px;">Terms & Conditions</h3>

<p>Welcome to  website (the "www.lnxx.com")/ My Account (the "Mobile Application").Lnxx world provides its services to you subject to the following conditions. Before you may use the Site / Mobile Application, you must read and accept all of the terms and conditions in, and linked to, this Terms & Conditions, the linked Privacy Policy and other Legal and Admin Lnxx.<br>
We strongly recommend that, as you read this ToU, you also access and read the linked information, since it is incorporated into and hereby made part of this ToU. This ToU is effective upon acceptance. Use of any functionality of the Site / Mobile Application constitutes acceptance of this ToU. If this ToU conflicts with any other documents, the ToU will control for the purposes of usage of the Site / Mobile Application. If you do not agree to be bound by this ToU and the Privacy Policy, you may not use the Site / Mobile Application in any way. Be sure to return to this page periodically to review the most current version of the ToU. We reserve the right, at any time, at our sole discretion, to change or otherwise modify the TOU without prior notice, and your continued access or use of this Site / Mobile Application signifies your acceptance of the updated or modified TOU.<br><br>
You understand that in case of your non-compliance (intentional or otherwise) with the Privacy Policy, Terms of Use and other Legal and Admin Policies for access or usage of the Site / Mobile Application,  reserves the right to terminate your access to the Site / Mobile Application and/or your account (“collectively referred to as Access”) or remove such non-compliant information (if any) provided by you, or both.
<br>
By agreeing to these Terms Of Use, you hereby provide a formal mandate to lnxx to represent you to the insurer and communicate the grant of a cover to you after effecting the insurance. Such mandate shall be valid for a period of 18 months, unless otherwise agreed between lnxx and you. Please note that no mandate is required for pre-underwritten policies or individual policies.
<br><br>
<b>1. Description of Services</b>
In the Site / Mobile Application, lnxx provides users with access to information primarily about Financial and Insurance products and services including but not restricted to General Insurance, Life Insurance products and related services (including but not limited to renewals) (the "Service"). You are responsible for obtaining access to the Site / Mobile Application, and that access may involve third-party fees (such as Internet service provider or airtime charges). In addition, you must provide and are responsible for all equipment necessary to access the Site / Mobile Application. By making use of this Site / Mobile Application, and furnishing your personal / contact details, you hereby agree that you are interested in availing and purchasing the Service(s) that you have selected. You hereby agree that lnxx may contact you either electronically or through phone, to understand your interest in the selected products and Service(s) (like renewals, reminders etc.) and to fulfill your demand. You also agree that lnxx reserves the right to make your details available to its affiliates and partners and you may be contacted by the affiliates and partners for information and for sales through email, telephone and/or sms. You agree to receive promotional materials and/or special offers from lnxx through email or sms.
<br><br>
<b>2. License and Site / Mobile Application Access</b>
lnxx grants you a limited license to access and make personal use of the Site / Mobile Application and the Service. This license does not include any downloading or copying of any kind of information for the benefit of another individual, vendor or any other third party; caching, unauthorized hypertext links to the Site / Mobile Application and the framing of any Content available through the Site / Mobile Application uploading, posting, or transmitting any content that you do not have a right to make available (such as the intellectual property of another party); uploading, posting, or transmitting any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; any action that imposes or may impose (in lnxx's sole discretion) an unreasonable or disproportionately large load on lnxx's infrastructure; or any use of data mining, robots, or similar data gathering and extraction tools. You may not bypass any measures used by lnxx to prevent or restrict access to the Site / Mobile Application. Any unauthorized use by you shall terminate the permission or license granted to you by lnxx. By using the Site / Mobile Application you agree not to: (i) use this Site / Mobile Application or its contents for any commercial purpose; (ii) make any speculative, false, or fraudulent transaction or any transaction in anticipation of demand; (iii) access, monitor or copy any content or information of this Site / Mobile Application using any robot, spider, scraper or other automated means or any manual process for any purpose without our express written permission; (iv) violate the restrictions in any robot exclusion headers on this Site / Mobile Application or bypass or circumvent other measures employed to prevent or limit access to this Site / Mobile Application; (v) take any action that imposes, or may impose, in our discretion, an unreasonable or disproportionately large load on our infrastructure; (vi) deep-link to any portion of this Site / Mobile Application (including, without limitation, the purchase path for any service) for any purpose without our express written permission; or (vii) "frame", "mirror" or otherwise incorporate any part of this Site / Mobile Application into any other website without our prior written authorization.
<br><br>
<b>3. Eligibility</b>
The Service is not available to minors under the age of 18 or to any users suspended or removed from the system by lnxx for any reason. Users may not have more than one active account. Additionally, users are prohibited from selling, trading, or otherwise transferring their accounts to another party. If you do not qualify, you may not use the Service or the Site / Mobile Application.
<br><br>
<b>4. Your Account</b>
In consideration of your use of the Site / Mobile Application, you represent that you are of legal age to form a binding contract and are not a person barred from receiving services under the laws of India or other applicable jurisdiction and will only use the Site / Mobile Application to make legitimate purchases for you or for another person for whom you are legally authorized to act (and will inform such other persons about the ToU and/or Privacy Policy) that apply to the purchase you have made on their behalf (including all rules and restrictions applicable thereto). You also agree to provide true, accurate, current and complete information about yourself as prompted by the Site / Mobile Application. If you provide any information that is untrue, inaccurate, not current or incomplete (or becomes untrue, inaccurate, not current or incomplete), or lnxx has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, lnxx has the right to suspend or terminate your account and refuse any and all current or future use of the Site / Mobile Application (or any portion thereof). If you use the Site / Mobile Application, you are responsible for maintaining the confidentiality of your account and password, and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your account or password. Because of this, we strongly recommend that you exit from your account at the end of each session. You agree to notify lnxx immediately of any unauthorized use of your account or any other breach of security. lnxx reserves the right to refuse service, terminate accounts, or remove or edit content in its sole discretion. Notwithstanding the above, we retain the right at our sole discretion to deny access to anyone to the Site / Mobile Application and the Services we offer, at any time and for any reason, including, but not limited to, for violation of the ToU or Privacy Policy. Additional terms and conditions will apply to your purchase of Services that you select. Please read these additional terms and conditions carefully. You agree to abide by the terms and conditions of purchase imposed by any service provider with whom you elect to deal, including, but not limited to, payment of all amounts when due and compliance with the service provider's rules and restrictions regarding use of products, and/or Services. You agree that any violation of any such service provider's rules and restrictions may result in cancellation of your purchase(s), in your being denied access to the applicable service(s), in your forfeiting any monies paid for such Services, and/or in our debiting your account for any costs we incur as a result of such violation.
<br><br>
<b>5. Submitted Content</b>
lnxx does not claim ownership of any materials you make available through the Site / Mobile Application. At lnxx's sole discretion, such materials may be included in the Service in whole or in part or in a modified form. With respect to such materials you submit or make available for inclusion on the Site / Mobile Application, you grant lnxx a perpetual, irrevocable, non-terminable, worldwide, royalty-free and non-exclusive license to use, copy, distribute, publicly display, modify, create derivative works, and sublicense such materials or any part of such materials (as well as use the name that you submit in connection with such submitted content). You hereby represent, warrant and covenant that any materials you provide do not include anything (including, but not limited to, text, images, music or video) to which you do not have the full right to grant the license specified in this Section 4. We take no responsibility and assume no liability for any submitted content posted or submitted by you. We have no obligation to post your comments; we reserve the right in our absolute discretion to determine which comments are published on the Site / Mobile Application. If you do not agree to these terms and conditions, please do not provide us with any submitted content. You agree that you are fully responsible for the content you submit. You are prohibited from posting or transmitting to or from this Site / Mobile Application: (i) any unlawful, threatening, libelous, defamatory, obscene, pornographic, or other material or content that would violate rights of publicity and/or privacy or that would violate any law; (ii) any commercial material or content (including, but not limited to, solicitation of funds, advertising, or marketing of any good or services); and (iii) any material or content that infringes, misappropriates or violates any copyright, trademark, patent right or other proprietary right of any third party. You shall be solely liable for any damages resulting from any violation of the foregoing restrictions, or any other harm resulting from your posting of content to this Site / Mobile Application.
<br><br>
<b>6. Disclaimer of Online Availability,Impressions, And Click-Throughs</b>
In addition to the other disclaimers and limitations discussed in this notice, there are no guarantees and no warranties regarding online availability, impressions, and click-through of www.lnxx.com, its web pages, and any material, information, links, or content presented on the web pages at www.lnxx.com. lnxx.com, its web pages, and any material, information, links, or content presented on the web pages at www.lnxx.com, may be unavailable for online access at anytime. Advertising sponsors and advertising,if any and if permitted, must be approved by lnxx before the posting of any advertising material, information, links, content, banners, and graphics on www.lnxx.com. lnxx reserves the right to accept or to reject any advertising sponsor or any advertising for any reason
<br><br>
<b>7. Cancellation & Refund/Chargeback Terms and Conditions</b>
(a) Free look period Cancellation and Refund
As per the IRDAI rules and regulations, you have the right to cancel your insurance policy within 15(fifteen) days from the date of (online) receipt of insurance policy (referred to as “Free look period”) and refund of your premium amount shall be processed as per the applicable process and procedures followed by the insurer. This Free look facility can be availed only for Life and Health insurance policies, subject to certain other terms and conditions specified by IRDAI. We encourage all our customers to read the insurance policy document carefully and avail the free look facility in case the terms and conditions of the insurance policy document don’t match your insurance requirements. Further, you understand that once you place a cancellation request within the Free look period, the policy gets cancelled and entire premium is refunded to you subject to deduction of (i) charges pertaining to medical tests conducted (ii) administrative and service cost like stamp duty etc. and; (iii )Charges for mortality for the period the policy was in force. Please note such deduction is at the sole discretion of the insurer.</p>

</div>
</section>


<style type="text/css">
.terms_conditions p{
	font-size: 14px;
    text-align: justify;
}
</style>

@endsection    